repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier-plugin-packagejson@2.4.3
          - prettier-plugin-svelte@2.10.0
  - repo: local
    hooks:
      - id: check-ci
        name: check module status
        entry: npm ci
        language: system
        pass_filenames: false
      - id: build
        name: build
        entry: bash -c 'npm run build -- --force'
        language: system
        pass_filenames: false
